### PR TITLE
A few readme changes

### PR DESCRIPTION
**Pull request by bjorn3**
* Remove the rustup command for installing the necessary components. This is now done automatically.
* Add closing parenthesis in the license section.

### CODE REVIEW

**Comment by bjorn3** [comment]
The "Contributing and getting help" section will need to be changed as Mozilla IRC doesn't exist anymore. I don't know what a good place would be for questions though.

**Comment by DJMcNab** [comment]
There are `#wg-debugging` and `#dev-tools` in the [rust discord server](https://discord.gg/rust-lang). Although it might make more sense to quickly spin up a priroda specific discord server.

**Review by DJMcNab — APPROVED** [review]
These changes make sense.

**Comment by oli-obk** [comment]
I'd personally prefer to just refer to the miri zulip

**Pull request merged**
