### PR TITLE
Clarify in README how to obtain libstd with a full MIR

### PR DESCRIPTION
**Pull request by vakaras**

### CODE REVIEW

**Review by bjorn3 — APPROVED** [review]
Can you please rebase on top of master? This PR contains commits from your other PR that has already been merged.

**Comment by vakaras** [comment]
Rebased.

**Comment by bjorn3** [comment]
@oli-obk Is it fine if I merge this myself, or would you prefer me not to, given that it has been a while since I did anything with priroda?

**Comment by oli-obk** [comment]
You have complete autonomy here, feel free to merge things as you see fit.

**Pull request merged**
