### PR TITLE
Update for lastest miri and improve it a bit

### PR DESCRIPTION
**Pull request by bjorn3**
screenshot-2018-4-7 example rs

* edges are now colored
* all numeric types, bools and &str are now nicely formatted
* using next while inside a call doesnt step to inside the next function call when on a return terminator
* boxes are only as high as their contents (except for the mir graph)
* stepping over `StorageLive`, `StorageDead`, `Validate`, `EndRegion` and `Nop` by default
* add restart button
* **show the source code**
* **breakpoints**
* migrate to rocket
* **time traveling support ↺**

## TODO
* change the miri submodule from my own fork to upstream when solson/miri#361 is merged

Source of the example:
```rust
#![feature(termination_trait)]

fn return_42() -> u64 {
    42
}

fn main() -> Result<(), std::io::Error> {
    let abc = Box::new(0);
    return_42();
    let f = 1.4f64;
    let sum = 1f64
    +
    f;
    let s = "ieeoe";
    let bcd: Box<[u8]> = Box::new([0, 1]);
    let d = true;
    format!("ewioio: {}", abc);
    Ok(())
}
```

Several edits: updated example, screenshot and feature list

### CODE REVIEW

**Comment by oli-obk** [comment]
I haven't forgotten about this. I'm trying to get miri working again atm :)

**Comment by bjorn3** [comment]
No problem

**Comment by bjorn3** [comment]
I added breakpoint support 🎊

**Comment by bjorn3** [comment]
Added time traveling support ↺

You can now step backwards in time.

**Comment by oli-obk** [comment]
Haha nice. We should probably add a tooltip mentioning that it's a very expensive operation ^^

**Comment by bjorn3** [comment]
Yeah!

**Comment by bjorn3** [comment]
Miri is updated to master.

**Comment by oli-obk** [comment]
So much awesomeness today.

Thanks for all your cleanup and improvement work here. It's way more than "a bit"!

**Pull request merged**
